# Using numpy arrays

In [2]:
import numpy as np

Matrices can also be created by combining existing vectors using the np.column_stack() function:

In [5]:
v = np.array([-2,-2,-2,-2])
u = np.array([0,0,0,0])
w = np.array([3,3,3,3])

A = np.column_stack((v,u,w))
A

array([[-2,  0,  3],
       [-2,  0,  3],
       [-2,  0,  3],
       [-2,  0,  3]])

To access the shape of a matrix or vector once it’s been created as a NumPy array, we call the .shape attribute of the array variable:

In [10]:
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

The first index accesses the specific row, while the second index accesses the specific column. Note that rows and columns are zero-indexed. In this example, the output will be the following:

In [11]:
A = np.array([[1,2],[3,4]])
A[0,1]

2

In [14]:
vector_1 = np.array([-2,-6,2,3])
vector_2 = np.array([4,1,-3,8])
vector_3 = np.array([5,-7,9,0])

matrix = np.column_stack((vector_1, vector_2, vector_3))
matrix

array([[-2,  4,  5],
       [-6,  1, -7],
       [ 2, -3,  9],
       [ 3,  8,  0]])

In [15]:
matrix.shape

(4, 3)

In [18]:
#printing the third column of the matrix
matrix[:,2]

array([ 5, -7,  9,  0])

# Using NumPy for Linear Algebra Operations

multiplication between the NumPy array and the scalar:

In [19]:
A = np.array([[1,2],[3,4]])
4 * A

array([[ 4,  8],
       [12, 16]])

addition between the NumPy arrays.

In [20]:
A = np.array([[1,2],[3,4]])
B = np.array([[-4,-3],[-2,-1]])
A + B

array([[-3, -1],
       [ 1,  3]])

Vector dot products can be computed using the np.dot() function:

In [21]:
v = np.array([-1,-2,-3])
u = np.array([2,2,2])
np.dot(v,u)

-12

Matrix multiplication is computed using either the np.matmul() function or using the @ symbol as shorthand. It is important to note that using the typical Python multiplication symbol * will result in an elementwise multiplication instead.

In [22]:
A = np.array([[1,2],[3,4]])
B = np.array([[-4,-3],[-2,-1]])
np.matmul(A,B)

array([[ -8,  -5],
       [-20, -13]])

In [23]:
A@B

array([[ -8,  -5],
       [-20, -13]])

In [24]:
A*B

array([[-4, -6],
       [-6, -4]])

Excercise

In [27]:
A = np.array([[2,3,-4], [-2, 1, -3]])
# 2 x 3 matrix
B = np.array([[1,-1,4], [3,-3,3]])
# 3 x 2 matrix
C = np.array([[1, 2], [3, 4], [5, 6]])

In [28]:
#1
D = 4 * A - 2 * B
D

array([[  6,  14, -24],
       [-14,  10, -18]])

In [30]:
#2
E = A@C
E

array([[ -9,  -8],
       [-14, -18]])

In [32]:
#3
F = C@A
F

array([[ -2,   5, -10],
       [ -2,  13, -24],
       [ -2,  21, -38]])

Special Matrices

An identity matrix can be constructed using the np.eye() functions, which takes an integer argument that determines the n x n size of the square identity matrix.

In [34]:
identity = np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

A matrix or vector of all zeros can be constructed using the np.zeros() function, which takes in a tuple argument for the shape of the NumPy array filled with zeros.

In [37]:
# 5-element vector of zeros
zero_vector = np.zeros((5))
zero_vector

array([0., 0., 0., 0., 0.])

In [38]:
# 3x2 matrix of zeros
zero_matrix = np.zeros((3,2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

The transpose of a matrix can be accessed using the .T attribute of a NumPy array as shown below:

In [40]:
A = np.array([[1,2],[3,4]])
A.T


array([[1, 3],
       [2, 4]])

Example

In [42]:
A = np.array([[1,-1,1], [0,1,0], [-1,2,1]])
B = np.array([[0.5,1.5,-0.5], [0,1,0], [0.5,-0.5,0.5]])

Print out the matrix product of AB and the matrix product of BA.

In [43]:
A@B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
B@A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Since the matrix product of A and B results in the identity matrix, they are inverses of each other.

In [45]:
A.T

array([[ 1,  0, -1],
       [-1,  1,  2],
       [ 1,  0,  1]])

In [46]:
B.T

array([[ 0.5,  0. ,  0.5],
       [ 1.5,  1. , -0.5],
       [-0.5,  0. ,  0.5]])

# Additional Linear Algebra Operations

The “norm” (or length/magnitude) of a vector can be found using np.linalg.norm():

In [49]:
v = np.array([2,-4,1])
v_norm = np.linalg.norm(v)
v_norm

4.58257569495584

## The inverse 
of a square matrix, if one exists, can be found using np.linalg.inv():

In [51]:
A = np.array([[1,2],[3,4]])
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

inally, we can actually solve for unknown variables in a system on linear equations in Ax=b form using np.linalg.solve(), which takes in the A and b parameters. Given:

In [55]:
# each array in A is an equation from the above system of equations
A = np.array([[1,4,-1],[-1,-3,2],[2,-1,-2]])
# the solution to each equation
b = np.array([-1,2,-2])
# solve for x, y, and z
x,y,z = np.linalg.solve(A,b)
x,y,z

(0.0, 0.0, 1.0)